import type { CSSProperties } from "react";

/** Co-located styles for the skill Evals tab tree (specs/15-skill-eval-cases.md
 *  §11). Mirrors the shipped agent tab's `styles.ts` shape for the pieces
 *  this tab shares (wrap/header/section/table), plus a few skill-only keys
 *  (effect row, gate-bypass/lift-zero notices, modal body). */
export const s = {
  wrap: { maxWidth: 900, display: "flex", flexDirection: "column", gap: 24 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  headSpacer: { marginLeft: "auto" } satisfies CSSProperties,
  tiles: { display: "flex", gap: 12, flexWrap: "wrap" } satisfies CSSProperties,
  section: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  sectionHead: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 } satisfies CSSProperties,
  th: {
    textAlign: "left",
    padding: "8px 10px",
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  td: { padding: "8px 10px", borderBottom: "1px solid var(--border)", color: "var(--text-secondary)" } satisfies CSSProperties,
  outcome: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12.5,
    fontWeight: 600,
    color,
  }),
  effectRow: { display: "flex", gap: 16, flexWrap: "wrap" } satisfies CSSProperties,
  effectCount: { display: "flex", alignItems: "center", gap: 6, fontSize: 13 } satisfies CSSProperties,
  notice: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--warn)",
    fontWeight: 600,
  } satisfies CSSProperties,
  form: { display: "flex", flexDirection: "column", gap: 16, padding: "20px 24px" } satisfies CSSProperties,
  formField: { display: "flex", flexDirection: "column", gap: 6, flex: 1 } satisfies CSSProperties,
  formRow: { display: "flex", gap: 12 } satisfies CSSProperties,
  label: { fontSize: 12.5, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  modalBody: { padding: "20px 24px", display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  footer: { display: "flex", justifyContent: "flex-end", gap: 10 } satisfies CSSProperties,
  tile: {
    flex: 1,
    minWidth: 130,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 9,
    padding: 14,
  } satisfies CSSProperties,
  tileLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.03em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tileValue: { fontSize: 24, fontWeight: 700, marginTop: 8 } satisfies CSSProperties,
  tileDelta: (color: string): CSSProperties => ({ fontSize: 12.5, fontWeight: 600, color, marginTop: 4 }),
  pre: {
    margin: 0,
    padding: 12,
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  diffLine: (kind: "added" | "removed" | "context"): CSSProperties => ({
    color: kind === "added" ? "var(--ok, var(--text-secondary))" : kind === "removed" ? "var(--crit)" : "var(--text-secondary)",
  }),
  callout: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
} as const;
